headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/jasonyin/project/electromechanical-landing/new-website/out"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/jasonyin/project/electromechanical-landing/new-website"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff2"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/zh/"

[headers.values]
Link = "<https://cute-jelly-dc03bf.netlify.app/zh/>; rel=\"alternate\"; hreflang=\"zh\", <https://cute-jelly-dc03bf.netlify.app/en/>; rel=\"alternate\"; hreflang=\"en\", <https://cute-jelly-dc03bf.netlify.app/th/>; rel=\"alternate\"; hreflang=\"th\", <https://cute-jelly-dc03bf.netlify.app/vi/>; rel=\"alternate\"; hreflang=\"vi\", <https://cute-jelly-dc03bf.netlify.app/ms/>; rel=\"alternate\"; hreflang=\"ms\", <https://cute-jelly-dc03bf.netlify.app/id/>; rel=\"alternate\"; hreflang=\"id\", <https://cute-jelly-dc03bf.netlify.app/es/>; rel=\"alternate\"; hreflang=\"es\", <https://cute-jelly-dc03bf.netlify.app/pt/>; rel=\"alternate\"; hreflang=\"pt\", <https://cute-jelly-dc03bf.netlify.app/zh/>; rel=\"alternate\"; hreflang=\"x-default\""

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/"
to = "/zh/"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/zh/*"
to = "/zh/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/en/*"
to = "/en/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/th/*"
to = "/th/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/vi/*"
to = "/vi/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/ms/*"
to = "/ms/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/id/*"
to = "/id/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/es/*"
to = "/es/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pt/*"
to = "/pt/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_next/image/"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]